<?php
$title = "Menadžer studenata";
$this->headTitle($title);
?>
<div class="jumbotron">
	<h1><span class="zf-green"><?php echo $this->escapeHtml($title)?></span></h1>
	<p>Ovo je program namenjen upravljanju bazom studenata i praćenjem njihovih aktivnosti na prijavljenim predmetima.</p>
</div>

<?php if(isset($SubjectData) && count($SubjectData) > 0): ?>
<div class="row">
<?php for($i = 0; $i < count($SubjectData); $i ++):?>
<?php if($i != 0 && $i % 3 == 0): ?>
</div>
<div class="row">
<?php endif;?>
<?php $subjectEntry = $SubjectData[$i]; ?>
<div class="col-sm-4">
    <div class="panel panel-default">
        <a href="<?php echo $this->url('predmeti', ['action' => 'preview', 'id' => $subjectEntry['id']]) ?>">
                <div class="panel-heading"><strong><?php echo $subjectEntry['sifra']?></strong> - <span class="zf-green"><?php echo $subjectEntry['ime'] ?></span></div>
        </a>
        <div class="panel-body">
            <ul>
                <li><span style="font-weight: 600">Upisano studenata:</span> <span class="zf-green"><?php echo $subjectEntry['totalStudents'] ?></span></li>
                <li><span style="font-weight: 600">Kolokvijum 1 položen:</span> <span class="zf-green"><?php echo $subjectEntry['c1attended'] ?></span></li>
                <li><span style="font-weight: 600">Kolokvijum 2 položen:</span> <span class="zf-green"><?php echo $subjectEntry['c2attended'] ?></span></li>
                <li><span style="font-weight: 600">Pismeni položen:</span> <span class="zf-green"><?php echo $subjectEntry['writtenAttended'] ?></span></li>
                <li><span style="font-weight: 600">Usmeni položen:</span> <span class="zf-green"><?php echo $subjectEntry['spokenAttended'] ?></span></li>
            </ul>
        </div>
    </div>
</div>
<?php endfor;?>
</div>
<?php endif;?>