<?php
$title = "Spisak ispitnih rokova za školsku godinu 2018/2019";
$this->headTitle($title);
$count = $rokovi->count();
?>

<h1 style="margin-bottom: 30px"><?php echo $this->escapehtml($title) ?></h1>

<?php if($count == 0): ?>
<p>Još uvek nema unesenih ispitnih rokova. Da li biste možda uneli jednog ili više njih?</p>
<?php else: ?>
<table class="table table-striped table-bordered" id="mainTable">
    <thead>
        <tr class="success">
            <th>R.br.</th>
            <th>Naziv</th>
            <th>Školska godina</th>
            <th>Počinje</th>
            <th>Završava se</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($rokovi as $rok): ?>
        <tr>
            <td><?php echo $rok->Id ?></td>
            <td><?php echo $rok->Name ?></td>
            <td><?php echo $rok->Year ?></td>
            <td><?php echo $rok->DateBeginning ?></td>
            <td><?php echo $rok->DateEnding ?></td>

            <td><a href="<?php echo $this->url('rokovi', ['action' => 'edit', 'id' => $rok->Id]) ?>">Promeni</a> | 
            <a id="delete" href="<?php echo $this->url('rokovi', ['action' => 'delete', 'id' => $rok->Id]) ?>" data-name="<?= $rok->Name?>">Obriši</a></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>
<p style="margin-top: 20px"><a class="btn btn-primary" href="<?php echo $this->url('rokovi', ['action' => 'add'])?>">Dodaj novi rok >>></a></p>

<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">Brisanje ispitnog roka</h4>
            </div>
            <div class="modal-body" id="message">
                    <p>Ispitni rok će biti potpuno obrisan iz baze, bez mogućnosti povratka podataka. Da li ste sigurni?</p>
            </div>
            <div class="modal-footer">
                    <button type="button" class="btn btn-confirm" data-dismiss="modal">Da</button>
                    <button type="button" class="btn btn-cancel" data-dismiss="modal">Ne</button>
            </div>
        </div>
    </div>
</div>

<script>
$(document).ready(function() {
    $('#mainTable').DataTable();
    $('a#delete').on('click', function(e) {
        e.preventDefault();
        path = $(e.target).attr('href');
        var name = $(e.target).data('name');
        $('#myModal').find('#message').text("Ispitni rok '" + name + "' će biti obrisan(a). Da li ste sigurni?");
        //console.log(path);
        $('#myModal').modal('show');
    });

    $('.btn-confirm').on('click', function(e) {        
        //alert(path);
        window.location.href = path;
    });
});
</script>