<?php

if(! isset($id))
    $title = "Dodaj novi predmet";
else 
    $title = "Promeni podatke o predmetu";

$this->headtitle($title);
?>

<h1><?php echo $this->escapehtml($title) ?></h1>

<?php 
    $sifra = $form->get('sifra');
    $sifra->setAttribute('class', 'form-control');
    $sifra->setAttribute('placeholder', 'Šifra predmeta ...');
    
    $ime = $form->get('ime');
    $ime->setAttribute('class', 'form-control');
    $ime->setAttribute('placeholder', 'Ime predmeta ...');
    
    $opis = $form->get('opis');
    $opis->setAttribute('class', 'form-control');
    $opis->setAttribute('placeholder', 'Kratak opis ...');
    
    $fond_casova = $form->get('fond_casova');
    $fond_casova->setAttribute('class', 'form-control');
    
    $profesor = $form->get('profesor');
    $profesor->setAttribute('class', 'form-control');
    $profesor->setAttribute('placeholder', 'Premetni profesor ...');
    
    $submit = $form->get('submit');
    $submit->setAttribute('class', 'btn btn-primary');
    
    if(! isset($id))
        $form->setAttribute('action', $this->url('predmeti', ['action' => 'add']));
    else 
        $form->setAttribute('action', $this->url('predmeti', ['action' => 'edit']));
    
    $form->prepare();
    
    echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?php echo $this->formLabel($sifra) ?>
    <div class='col-xs-4'>
        <?php echo $this->formElement($sifra);?>
        <?php echo $this->formElementErrors()->render($sifra, ['class' => 'help-block']) ?>
    </div>
</div>

<div class='form-group'>
    <?php echo $this->formLabel($ime) ?>
    <div class='col-xs-4'>
        <?php echo $this->formElement($ime);?>
        <?php echo $this->formElementErrors()->render($ime, ['class' => 'help-block']) ?>
    </div>
</div>

<div class='form-group'>
    <?php echo $this->formLabel($opis) ?>
    <div class='col-xs-4'>
        <?php echo $this->formElement($opis);?>
        <?php echo $this->formElementErrors()->render($opis, ['class' => 'help-block']) ?>
    </div>
</div>

<div class='form-group'>
    <?php echo $this->formLabel($fond_casova) ?>
    <div class='col-xs-4'>
        <?php echo $this->formElement($fond_casova);?>
        <?php echo $this->formElementErrors()->render($fond_casova, ['class' => 'help-block']) ?>
    </div>
</div>

<div class='form-group'>
    <?php echo $this->formLabel($profesor) ?>
    <div class='col-xs-4'>
        <?php echo $this->formElement($profesor);?>
        <?php echo $this->formElementErrors()->render($profesor, ['class' => 'help-block']) ?>
    </div>
</div>
<div class="form-group" >
	<div class="col-xs-offset-2 col-xs-4">
        <?php echo $this->formSubmit($submit) ?>
        <a href="<?php echo $this->url('predmeti')?>" class="btn btn-default">Nazad</a>
    </div>
</div>
<?php 
    echo $this->formHidden($form->get('id'));
    echo $this->form()->closeTag();    
?>


