<?php
$title = "Spisak predmeta";
$this->headtitle($title);
$count = $subjects->count();
?>

<h1><?php echo $this->escapehtml($title) ?></h1>

<?php if($count == 0): ?>
<p>Još uvek nema unesenih predmeta. Da li biste možda uneli jednog ili više njih?</p>
<?php else: ?>
<table class="table table-striped" id="mainTable">
	<thead>
            <tr class="success">
                <th>Ime</th>
                <th>Fond casova</th>
                <th>Profesor</th>
                <th>Akcija</th>
            </tr>
	</thead>
	<tbody>
	<?php foreach($subjects as $subject): ?>
	<tr>
		<td><?php echo $subject->ime ?></td>
		<td><?php echo $subject->fond_casova ?></td>
		<td><?php echo $subject->profesor ?></td>
		<td><a href="<?php echo $this->url('predmeti', ['action' => 'edit', 'id' => $subject->id]) ?>">Izmeni</a> | 
		<a id="delete" href="<?php echo $this->url('predmeti', ['action' => 'deleteWithModel', 'id' => $subject->id]) ?>" data-name="<?= $subject->ime?>">Izbriši</a></td>
	</tr>
	<?php endforeach; ?>
	</tbody>
</table>

<p><a class="btn btn-primary" href="<?php echo $this->url('predmeti', ['action' => 'add'])?>">Dodaj novi predmet >>></a></p>


<?php endif; ?>

<div class="modal fade" id="myModal" role="dialog">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title">Brisanje predmeta</h4>
			</div>
			<div class="modal-body" id="message">
				<p>Predmet će biti potpuno obrisan iz baze, bez mogućnosti povratka podataka. Da li ste sigurni?</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-confirm" data-dismiss="modal">Da</button>
				<button type="button" class="btn btn-cancel" data-dismiss="modal">Ne</button>
			</div>
		</div>
	</div>
</div>
<script>
$(document).ready(function() {
    $('#mainTable').DataTable();
    $('a#delete').on('click', function(e) {
        e.preventDefault();
        path = $(e.target).attr('href');
        var name = $(e.target).data('name');
        $('#myModal').find('#message').text("Predmet '" + name + "' će biti obrisan(a). Da li ste sigurni?");
        $('#myModal').modal('show');
    });

    $('.btn-confirm').on('click', function(e) {        
        window.location.href = path;
    });
});
</script>